sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 262412
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket-name: springboot-demo1
    access-key-id: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
    access-key-secret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
  redis:
    host: 192.168.200.130
    port: 6379
    password: leadnews
    database: 0

